//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.18 at 03:45:10 PM EST 
//


package com.springsource.hq.plugin.tcserver.cli.client.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Response">
 *       &lt;sequence>
 *         &lt;element name="JvmOptions" type="{}JvmOptions"/>
 *         &lt;element name="StatusResponse" type="{}StatusResponse" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jvmOptions",
    "statusResponse"
})
@XmlRootElement(name = "JvmOptionsResponse")
public class JvmOptionsResponse
    extends Response
{

    @XmlElement(name = "JvmOptions", required = true)
    protected JvmOptions jvmOptions;
    @XmlElement(name = "StatusResponse", required = true)
    protected List<StatusResponse> statusResponse;

    /**
     * Gets the value of the jvmOptions property.
     * 
     * @return
     *     possible object is
     *     {@link JvmOptions }
     *     
     */
    public JvmOptions getJvmOptions() {
        return jvmOptions;
    }

    /**
     * Sets the value of the jvmOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JvmOptions }
     *     
     */
    public void setJvmOptions(JvmOptions value) {
        this.jvmOptions = value;
    }

    /**
     * Gets the value of the statusResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatusResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusResponse }
     * 
     * 
     */
    public List<StatusResponse> getStatusResponse() {
        if (statusResponse == null) {
            statusResponse = new ArrayList<StatusResponse>();
        }
        return this.statusResponse;
    }

    @Override
    public boolean equals(Object that) {
        return EqualsBuilder.reflectionEquals(this, that);
    }

    @Override
    public int hashCode() {
        return HashCodeBuilder.reflectionHashCode(this);
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }

}
