//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="https://java.sun.com/xml/jaxb">https://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.18 at 03:45:10 PM EST 
//


package com.springsource.hq.plugin.tcserver.cli.client.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.springsource.hq.plugin.tcserver.cli.client.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.springsource.hq.plugin.tcserver.cli.client.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link JvmOptionsRequest }
     * 
     */
    public JvmOptionsRequest createJvmOptionsRequest() {
        return new JvmOptionsRequest();
    }

    /**
     * Create an instance of {@link JvmOptionsGroupRequest }
     * 
     */
    public JvmOptionsGroupRequest createJvmOptionsGroupRequest() {
        return new JvmOptionsGroupRequest();
    }

    /**
     * Create an instance of {@link ServiceError }
     * 
     */
    public ServiceError createServiceError() {
        return new ServiceError();
    }

    /**
     * Create an instance of {@link Host }
     * 
     */
    public Host createHost() {
        return new Host();
    }

    /**
     * Create an instance of {@link GroupsResponse }
     * 
     */
    public GroupsResponse createGroupsResponse() {
        return new GroupsResponse();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link JvmOptions }
     * 
     */
    public JvmOptions createJvmOptions() {
        return new JvmOptions();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link ConfigurationStatusResponse }
     * 
     */
    public ConfigurationStatusResponse createConfigurationStatusResponse() {
        return new ConfigurationStatusResponse();
    }

    /**
     * Create an instance of {@link StatusResponse }
     * 
     */
    public StatusResponse createStatusResponse() {
        return new StatusResponse();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link ControlStatusResponse }
     * 
     */
    public ControlStatusResponse createControlStatusResponse() {
        return new ControlStatusResponse();
    }

    /**
     * Create an instance of {@link ResourcesResponse }
     * 
     */
    public ResourcesResponse createResourcesResponse() {
        return new ResourcesResponse();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link JvmOptionsResponse }
     * 
     */
    public JvmOptionsResponse createJvmOptionsResponse() {
        return new JvmOptionsResponse();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link ApplicationManagementResponse }
     * 
     */
    public ApplicationManagementResponse createApplicationManagementResponse() {
        return new ApplicationManagementResponse();
    }

}
