//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="https://java.sun.com/xml/jaxb">https://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.18 at 03:45:10 PM EST 
//


package com.springsource.hq.plugin.tcserver.cli.client.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Operation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Operation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="createPlatform"/>
 *     &lt;enumeration value="modifyPlatform"/>
 *     &lt;enumeration value="removePlatform"/>
 *     &lt;enumeration value="addServer"/>
 *     &lt;enumeration value="viewPlatform"/>
 *     &lt;enumeration value="monitorPlatform"/>
 *     &lt;enumeration value="controlPlatform"/>
 *     &lt;enumeration value="managePlatformAlerts"/>
 *     &lt;enumeration value="createServer"/>
 *     &lt;enumeration value="modifyServer"/>
 *     &lt;enumeration value="removeServer"/>
 *     &lt;enumeration value="addService"/>
 *     &lt;enumeration value="viewServer"/>
 *     &lt;enumeration value="monitorServer"/>
 *     &lt;enumeration value="controlServer"/>
 *     &lt;enumeration value="manageServerAlerts"/>
 *     &lt;enumeration value="createService"/>
 *     &lt;enumeration value="modifyService"/>
 *     &lt;enumeration value="removeService"/>
 *     &lt;enumeration value="viewService"/>
 *     &lt;enumeration value="monitorService"/>
 *     &lt;enumeration value="controlService"/>
 *     &lt;enumeration value="manageServiceAlerts"/>
 *     &lt;enumeration value="createApplication"/>
 *     &lt;enumeration value="modifyApplication"/>
 *     &lt;enumeration value="removeApplication"/>
 *     &lt;enumeration value="viewApplication"/>
 *     &lt;enumeration value="monitorApplication"/>
 *     &lt;enumeration value="controlApplication"/>
 *     &lt;enumeration value="manageApplicationAlerts"/>
 *     &lt;enumeration value="createResourceGroup"/>
 *     &lt;enumeration value="viewResourceGroup"/>
 *     &lt;enumeration value="manageGroupAlerts"/>
 *     &lt;enumeration value="modifyResourceGroup"/>
 *     &lt;enumeration value="addRole"/>
 *     &lt;enumeration value="removeResourceGroup"/>
 *     &lt;enumeration value="controlResourceGroup"/>
 *     &lt;enumeration value="monitorResourceGroup"/>
 *     &lt;enumeration value="viewRole"/>
 *     &lt;enumeration value="createRole"/>
 *     &lt;enumeration value="modifyRole"/>
 *     &lt;enumeration value="removeRole"/>
 *     &lt;enumeration value="viewSubject"/>
 *     &lt;enumeration value="modifySubject"/>
 *     &lt;enumeration value="removeSubject"/>
 *     &lt;enumeration value="createSubject"/>
 *     &lt;enumeration value="administerCAM"/>
 *     &lt;enumeration value="createEscalation"/>
 *     &lt;enumeration value="modifyEscalation"/>
 *     &lt;enumeration value="removeEscalation"/>
 *     &lt;enumeration value="viewEscalation"/>
 *     &lt;enumeration value="createResource"/>
 *     &lt;enumeration value="modifyResourceType"/>
 *     &lt;enumeration value="addOperation"/>
 *     &lt;enumeration value="removeOperation"/>
 *     &lt;enumeration value="viewPolicy"/>
 *     &lt;enumeration value="createPolicy"/>
 *     &lt;enumeration value="modifyPolicy"/>
 *     &lt;enumeration value="removePolicy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Operation")
@XmlEnum
public enum Operation {

    @XmlEnumValue("createPlatform")
    CREATE_PLATFORM("createPlatform"),
    @XmlEnumValue("modifyPlatform")
    MODIFY_PLATFORM("modifyPlatform"),
    @XmlEnumValue("removePlatform")
    REMOVE_PLATFORM("removePlatform"),
    @XmlEnumValue("addServer")
    ADD_SERVER("addServer"),
    @XmlEnumValue("viewPlatform")
    VIEW_PLATFORM("viewPlatform"),
    @XmlEnumValue("monitorPlatform")
    MONITOR_PLATFORM("monitorPlatform"),
    @XmlEnumValue("controlPlatform")
    CONTROL_PLATFORM("controlPlatform"),
    @XmlEnumValue("managePlatformAlerts")
    MANAGE_PLATFORM_ALERTS("managePlatformAlerts"),
    @XmlEnumValue("createServer")
    CREATE_SERVER("createServer"),
    @XmlEnumValue("modifyServer")
    MODIFY_SERVER("modifyServer"),
    @XmlEnumValue("removeServer")
    REMOVE_SERVER("removeServer"),
    @XmlEnumValue("addService")
    ADD_SERVICE("addService"),
    @XmlEnumValue("viewServer")
    VIEW_SERVER("viewServer"),
    @XmlEnumValue("monitorServer")
    MONITOR_SERVER("monitorServer"),
    @XmlEnumValue("controlServer")
    CONTROL_SERVER("controlServer"),
    @XmlEnumValue("manageServerAlerts")
    MANAGE_SERVER_ALERTS("manageServerAlerts"),
    @XmlEnumValue("createService")
    CREATE_SERVICE("createService"),
    @XmlEnumValue("modifyService")
    MODIFY_SERVICE("modifyService"),
    @XmlEnumValue("removeService")
    REMOVE_SERVICE("removeService"),
    @XmlEnumValue("viewService")
    VIEW_SERVICE("viewService"),
    @XmlEnumValue("monitorService")
    MONITOR_SERVICE("monitorService"),
    @XmlEnumValue("controlService")
    CONTROL_SERVICE("controlService"),
    @XmlEnumValue("manageServiceAlerts")
    MANAGE_SERVICE_ALERTS("manageServiceAlerts"),
    @XmlEnumValue("createApplication")
    CREATE_APPLICATION("createApplication"),
    @XmlEnumValue("modifyApplication")
    MODIFY_APPLICATION("modifyApplication"),
    @XmlEnumValue("removeApplication")
    REMOVE_APPLICATION("removeApplication"),
    @XmlEnumValue("viewApplication")
    VIEW_APPLICATION("viewApplication"),
    @XmlEnumValue("monitorApplication")
    MONITOR_APPLICATION("monitorApplication"),
    @XmlEnumValue("controlApplication")
    CONTROL_APPLICATION("controlApplication"),
    @XmlEnumValue("manageApplicationAlerts")
    MANAGE_APPLICATION_ALERTS("manageApplicationAlerts"),
    @XmlEnumValue("createResourceGroup")
    CREATE_RESOURCE_GROUP("createResourceGroup"),
    @XmlEnumValue("viewResourceGroup")
    VIEW_RESOURCE_GROUP("viewResourceGroup"),
    @XmlEnumValue("manageGroupAlerts")
    MANAGE_GROUP_ALERTS("manageGroupAlerts"),
    @XmlEnumValue("modifyResourceGroup")
    MODIFY_RESOURCE_GROUP("modifyResourceGroup"),
    @XmlEnumValue("addRole")
    ADD_ROLE("addRole"),
    @XmlEnumValue("removeResourceGroup")
    REMOVE_RESOURCE_GROUP("removeResourceGroup"),
    @XmlEnumValue("controlResourceGroup")
    CONTROL_RESOURCE_GROUP("controlResourceGroup"),
    @XmlEnumValue("monitorResourceGroup")
    MONITOR_RESOURCE_GROUP("monitorResourceGroup"),
    @XmlEnumValue("viewRole")
    VIEW_ROLE("viewRole"),
    @XmlEnumValue("createRole")
    CREATE_ROLE("createRole"),
    @XmlEnumValue("modifyRole")
    MODIFY_ROLE("modifyRole"),
    @XmlEnumValue("removeRole")
    REMOVE_ROLE("removeRole"),
    @XmlEnumValue("viewSubject")
    VIEW_SUBJECT("viewSubject"),
    @XmlEnumValue("modifySubject")
    MODIFY_SUBJECT("modifySubject"),
    @XmlEnumValue("removeSubject")
    REMOVE_SUBJECT("removeSubject"),
    @XmlEnumValue("createSubject")
    CREATE_SUBJECT("createSubject"),
    @XmlEnumValue("administerCAM")
    ADMINISTER_CAM("administerCAM"),
    @XmlEnumValue("createEscalation")
    CREATE_ESCALATION("createEscalation"),
    @XmlEnumValue("modifyEscalation")
    MODIFY_ESCALATION("modifyEscalation"),
    @XmlEnumValue("removeEscalation")
    REMOVE_ESCALATION("removeEscalation"),
    @XmlEnumValue("viewEscalation")
    VIEW_ESCALATION("viewEscalation"),
    @XmlEnumValue("createResource")
    CREATE_RESOURCE("createResource"),
    @XmlEnumValue("modifyResourceType")
    MODIFY_RESOURCE_TYPE("modifyResourceType"),
    @XmlEnumValue("addOperation")
    ADD_OPERATION("addOperation"),
    @XmlEnumValue("removeOperation")
    REMOVE_OPERATION("removeOperation"),
    @XmlEnumValue("viewPolicy")
    VIEW_POLICY("viewPolicy"),
    @XmlEnumValue("createPolicy")
    CREATE_POLICY("createPolicy"),
    @XmlEnumValue("modifyPolicy")
    MODIFY_POLICY("modifyPolicy"),
    @XmlEnumValue("removePolicy")
    REMOVE_POLICY("removePolicy");
    private final String value;

    Operation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Operation fromValue(String v) {
        for (Operation c: Operation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
